name: comic_check_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  hooks_riverpod: ^0.14.0+4
  state_notifier: ^0.7.0
  freezed_annotation: ^0.14.3
  json_serializable: ^4.1.4
  flutter_slidable: ^0.6.0
  flutter_screenutil: ^5.3.1
  shared_preferences: ^2.0.13
  settings_ui: ^2.0.2
  url_launcher: ^6.0.18
  in_app_review: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.2
  build_runner: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_list.png